import { InventoryTrackingTypeDto } from './dto/inventory.dto';

export const INVENTORY_SEED_CATEGORIES = [
  {
    name: 'Furniture',
    nameBn: 'আসবাবপত্র',
    slug: 'furniture',
    iconName: 'armchair',
    colorCode: '#854F0B',
    sortOrder: 1,
  },
  {
    name: 'Electronics & Appliances',
    nameBn: 'ইলেকট্রনিক্স',
    slug: 'electronics-appliances',
    iconName: 'monitor',
    colorCode: '#185FA5',
    sortOrder: 2,
  },
  {
    name: 'IT & Computer',
    nameBn: 'কম্পিউটার',
    slug: 'it-computer',
    iconName: 'laptop',
    colorCode: '#534AB7',
    sortOrder: 3,
  },
  {
    name: 'Lab Equipment',
    nameBn: 'ল্যাব সরঞ্জাম',
    slug: 'lab-equipment',
    iconName: 'flask',
    colorCode: '#0F6E56',
    sortOrder: 4,
  },
  {
    name: 'Sports Equipment',
    nameBn: 'ক্রীড়া সরঞ্জাম',
    slug: 'sports-equipment',
    iconName: 'trophy',
    colorCode: '#3B6D11',
    sortOrder: 5,
  },
  {
    name: 'Stationery & Supplies',
    nameBn: 'স্টেশনারি',
    slug: 'stationery-supplies',
    iconName: 'pencil',
    colorCode: '#444441',
    sortOrder: 6,
  },
  {
    name: 'Books & Library',
    nameBn: 'বই ও পাঠাগার',
    slug: 'books-library',
    iconName: 'book',
    colorCode: '#633806',
    sortOrder: 7,
  },
  {
    name: 'Cleaning & Maintenance',
    nameBn: 'পরিষ্কার সরঞ্জাম',
    slug: 'cleaning-maintenance',
    iconName: 'tool',
    colorCode: '#5F5E5A',
    sortOrder: 8,
  },
  {
    name: 'Musical Instruments',
    nameBn: 'বাদ্যযন্ত্র',
    slug: 'musical-instruments',
    iconName: 'music',
    colorCode: '#A32D2D',
    sortOrder: 9,
  },
  {
    name: 'Kitchen & Canteen',
    nameBn: 'রান্নাঘর ও ক্যান্টিন',
    slug: 'kitchen-canteen',
    iconName: 'coffee',
    colorCode: '#791F1F',
    sortOrder: 10,
  },
];

export const INVENTORY_SEED_ITEMS = [
  { categorySlug: 'furniture', name: '2-Seater Bench', code: 'FUR-BENCH-2', unit: 'piece', seatingCapacity: 2, isSeatingItem: true },
  { categorySlug: 'furniture', name: '3-Seater Bench', code: 'FUR-BENCH-3', unit: 'piece', seatingCapacity: 3, isSeatingItem: true },
  { categorySlug: 'furniture', name: '4-Seater Bench', code: 'FUR-BENCH-4', unit: 'piece', seatingCapacity: 4, isSeatingItem: true },
  { categorySlug: 'furniture', name: 'Single Desk & Chair', code: 'FUR-DESK-CHAIR-1', unit: 'set', seatingCapacity: 1, isSeatingItem: true },
  { categorySlug: 'furniture', name: 'Teacher Table', code: 'FUR-TEACHER-TABLE', unit: 'piece' },
  { categorySlug: 'furniture', name: 'Teacher Chair', code: 'FUR-TEACHER-CHAIR', unit: 'piece', seatingCapacity: 1, isSeatingItem: true },
  { categorySlug: 'furniture', name: 'Blackboard', code: 'FUR-BLACKBOARD', unit: 'piece' },
  { categorySlug: 'furniture', name: 'Whiteboard', code: 'FUR-WHITEBOARD', unit: 'piece' },
  { categorySlug: 'furniture', name: 'Steel Almirah', code: 'FUR-ALMIRAH-STEEL', unit: 'piece' },
  { categorySlug: 'furniture', name: 'Book Shelf / Rack', code: 'FUR-BOOK-SHELF', unit: 'piece' },

  { categorySlug: 'electronics-appliances', name: 'Ceiling Fan', code: 'ELEC-CEILING-FAN', unit: 'piece' },
  { categorySlug: 'electronics-appliances', name: 'Wall Fan', code: 'ELEC-WALL-FAN', unit: 'piece' },
  { categorySlug: 'electronics-appliances', name: 'Tube Light / LED Light', code: 'ELEC-LIGHT', unit: 'piece' },
  { categorySlug: 'electronics-appliances', name: 'Air Conditioner (AC)', code: 'ELEC-AC', unit: 'piece', trackingType: InventoryTrackingTypeDto.INDIVIDUAL, isDepreciable: true },
  { categorySlug: 'electronics-appliances', name: 'Projector', code: 'ELEC-PROJECTOR', unit: 'piece', trackingType: InventoryTrackingTypeDto.INDIVIDUAL, isDepreciable: true },
  { categorySlug: 'electronics-appliances', name: 'CCTV Camera', code: 'ELEC-CCTV', unit: 'piece', trackingType: InventoryTrackingTypeDto.INDIVIDUAL, isDepreciable: true },

  { categorySlug: 'it-computer', name: 'Desktop Computer', code: 'IT-DESKTOP', unit: 'piece', trackingType: InventoryTrackingTypeDto.INDIVIDUAL, isDepreciable: true },
  { categorySlug: 'it-computer', name: 'Laptop', code: 'IT-LAPTOP', unit: 'piece', trackingType: InventoryTrackingTypeDto.INDIVIDUAL, isDepreciable: true },
  { categorySlug: 'it-computer', name: 'Printer', code: 'IT-PRINTER', unit: 'piece', trackingType: InventoryTrackingTypeDto.INDIVIDUAL, isDepreciable: true },
  { categorySlug: 'it-computer', name: 'Router / Network Switch', code: 'IT-NETWORK', unit: 'piece', trackingType: InventoryTrackingTypeDto.INDIVIDUAL, isDepreciable: true },

  { categorySlug: 'lab-equipment', name: 'Microscope', code: 'LAB-MICROSCOPE', unit: 'piece', trackingType: InventoryTrackingTypeDto.INDIVIDUAL, isDepreciable: true },
  { categorySlug: 'lab-equipment', name: 'Lab Stool', code: 'LAB-STOOL', unit: 'piece', seatingCapacity: 1, isSeatingItem: true },
  { categorySlug: 'sports-equipment', name: 'Football', code: 'SPORT-FOOTBALL', unit: 'piece' },
  { categorySlug: 'sports-equipment', name: 'Cricket Bat', code: 'SPORT-CRICKET-BAT', unit: 'piece' },
  { categorySlug: 'stationery-supplies', name: 'A4 Paper', code: 'STAT-A4-PAPER', unit: 'ream', minimumStock: 5 },
  { categorySlug: 'stationery-supplies', name: 'Marker Pen', code: 'STAT-MARKER', unit: 'piece', minimumStock: 20 },
  { categorySlug: 'books-library', name: 'Library Book', code: 'LIB-BOOK', unit: 'piece' },
  { categorySlug: 'cleaning-maintenance', name: 'Broom', code: 'CLEAN-BROOM', unit: 'piece' },
  { categorySlug: 'musical-instruments', name: 'Harmonium', code: 'MUSIC-HARMONIUM', unit: 'piece', trackingType: InventoryTrackingTypeDto.INDIVIDUAL },
  { categorySlug: 'kitchen-canteen', name: 'Water Filter', code: 'KIT-WATER-FILTER', unit: 'piece', trackingType: InventoryTrackingTypeDto.INDIVIDUAL },
];
