export const PERMISSIONS = {
  SESSIONS: {
    CREATE: 'academics.sessions.create',
    VIEW: 'academics.sessions.view',
    EDIT: 'academics.sessions.edit',
    DELETE: 'academics.sessions.delete',
    ALL: 'academics.sessions.all',
  },
  SHIFTS: {
    CREATE: 'academics.shifts.create',
    VIEW: 'academics.shifts.view',
    EDIT: 'academics.shifts.edit',
    DELETE: 'academics.shifts.delete',
    ALL: 'academics.shifts.all',
  },
  CLASSES: {
    CREATE: 'academics.classes.create',
    VIEW: 'academics.classes.view',
    EDIT: 'academics.classes.edit',
    DELETE: 'academics.classes.delete',
    ALL: 'academics.classes.all',
  },
  CLASS_ROOMS: {
    CREATE: 'academics.class_rooms.create',
    VIEW: 'academics.class_rooms.view',
    EDIT: 'academics.class_rooms.edit',
    DELETE: 'academics.class_rooms.delete',
    ALL: 'academics.class_rooms.all',
  },
  SUBJECTS: {
    CREATE: 'academics.subjects.create',
    VIEW: 'academics.subjects.view',
    EDIT: 'academics.subjects.edit',
    DELETE: 'academics.subjects.delete',
    ALL: 'academics.subjects.all',
  },
  EXAMS: {
    CREATE: 'examinations.schedule.create',
    VIEW: 'examinations.schedule.view',
    EDIT: 'examinations.schedule.edit',
    DELETE: 'examinations.schedule.delete',
    ALL: 'examinations.schedule.all',
  },
  SYLLABUS: {
    CREATE: 'academics.syllabus.create',
    VIEW: 'academics.syllabus.view',
    EDIT: 'academics.syllabus.edit',
    DELETE: 'academics.syllabus.delete',
    ALL: 'academics.syllabus.all',
  },
  TIMETABLE: {
    CREATE: 'academics.timetable.create',
    VIEW: 'academics.timetable.view',
    EDIT: 'academics.timetable.edit',
    DELETE: 'academics.timetable.delete',
    ALL: 'academics.timetable.all',
  },
  ROLES: {
    VIEW: 'roles.view',
    ALL: 'roles.all',
    MANAGEMENT: {
      ALL: 'roles.management.all',
      VIEW: 'roles.management.view',
      CREATE: 'roles.management.create',
      EDIT: 'roles.management.edit',
      DELETE: 'roles.management.delete',
    },
    MATRIX: {
      ALL: 'roles.matrix.all',
      VIEW: 'roles.matrix.view',
      CREATE: 'roles.matrix.create',
      EDIT: 'roles.matrix.edit',
      DELETE: 'roles.matrix.delete',
    },
  },
  SCHOOLS_MANAGEMENT: {
    ALL: 'schools_management.all',
    SCHOOL_SUBSCRIPTIONS: {
      ALL: 'schools_management.school_subscriptions.all',
      VIEW: 'schools_management.school_subscriptions.view',
      CREATE: 'schools_management.school_subscriptions.create',
      EDIT: 'schools_management.school_subscriptions.edit',
      DELETE: 'schools_management.school_subscriptions.delete',
    },
    BANK_ACCOUNTS: {
      ALL: 'schools_management.bank_accounts.all',
      VIEW: 'schools_management.bank_accounts.view',
      CREATE: 'schools_management.bank_accounts.create',
      EDIT: 'schools_management.bank_accounts.edit',
      DELETE: 'schools_management.bank_accounts.delete',
    },
    PAYMENTS: {
      ALL: 'schools_management.payments.all',
      VIEW: 'schools_management.payments.view',
      CREATE: 'schools_management.payments.create',
      EDIT: 'schools_management.payments.edit',
      DELETE: 'schools_management.payments.delete',
    },
  },
  STAFF: {
    ALL: 'staff.all',
    VIEW: 'staff.view',
    DESIGNATIONS: {
      ALL: 'staff.designations.all',
      VIEW: 'staff.designations.view',
      CREATE: 'staff.designations.create',
      EDIT: 'staff.designations.edit',
      DELETE: 'staff.designations.delete',
    },
    DEPARTMENTS: {
      ALL: 'staff.departments.all',
      VIEW: 'staff.departments.view',
      CREATE: 'staff.departments.create',
      EDIT: 'staff.departments.edit',
      DELETE: 'staff.departments.delete',
    },
    TEACHERS: {
      ALL: 'staff.teachers.all',
      VIEW: 'staff.teachers.view',
      CREATE: 'staff.teachers.create',
      EDIT: 'staff.teachers.edit',
      DELETE: 'staff.teachers.delete',
    },
  },
  INVENTORY: {
      AUDIT_LOGS: {
        ALL: 'inventory.audit_logs.all',
        VIEW: 'inventory.audit_logs.view',
      },
    ALL: 'inventory.all',
    VIEW: 'inventory.view',
    CATEGORIES: {
      ALL: 'inventory.categories.all',
      VIEW: 'inventory.categories.view',
      CREATE: 'inventory.categories.create',
      EDIT: 'inventory.categories.edit',
      DELETE: 'inventory.categories.delete',
    },
    ITEMS: {
      ALL: 'inventory.items.all',
      VIEW: 'inventory.items.view',
      CREATE: 'inventory.items.create',
      EDIT: 'inventory.items.edit',
      DELETE: 'inventory.items.delete',
    },
    LOCATIONS: {
      ALL: 'inventory.locations.all',
      VIEW: 'inventory.locations.view',
      CREATE: 'inventory.locations.create',
      EDIT: 'inventory.locations.edit',
      DELETE: 'inventory.locations.delete',
    },
    STOCK: {
      ALL: 'inventory.stock.all',
      VIEW: 'inventory.stock.view',
      CREATE: 'inventory.stock.create',
      EDIT: 'inventory.stock.edit',
      DELETE: 'inventory.stock.delete',
    },
    ASSETS: {
      ALL: 'inventory.assets.all',
      VIEW: 'inventory.assets.view',
      CREATE: 'inventory.assets.create',
      EDIT: 'inventory.assets.edit',
      DELETE: 'inventory.assets.delete',
    },
    MOVEMENTS: {
      ALL: 'inventory.movements.all',
      VIEW: 'inventory.movements.view',
      CREATE: 'inventory.movements.create',
      EDIT: 'inventory.movements.edit',
      DELETE: 'inventory.movements.delete',
    },
    MAINTENANCE: {
      ALL: 'inventory.maintenance.all',
      VIEW: 'inventory.maintenance.view',
      CREATE: 'inventory.maintenance.create',
      EDIT: 'inventory.maintenance.edit',
      DELETE: 'inventory.maintenance.delete',
    },
  },
  ADMISSION: {
    ALL: 'admission.all',
    SETTINGS: {
      ALL: 'admission.settings.all',
      VIEW: 'admission.settings.view',
      EDIT: 'admission.settings.update',
    },
    APPLICATIONS: {
      ALL: 'admission.applications.all',
      VIEW: 'admission.applications.view',
      CREATE: 'admission.applications.create',
      EDIT: 'admission.applications.update',
      DELETE: 'admission.applications.delete',
      APPROVE: 'admission.applications.approve',
      REJECT: 'admission.applications.reject',
    },
  },
  STUDENTS: {
    ALL: 'students.all',
    DIRECTORY: {
      ALL: 'students.directory.all',
      VIEW: 'students.directory.view',
    },
    PAYMENTS: {
      ALL: 'students.payments.all',
      VIEW: 'students.payments.view',
    },
    PROFILE: {
      ALL: 'students.profile.all',
      VIEW: 'students.profile.view',
      EDIT: 'students.profile.update',
      STATUS: 'students.status.update',
      DELETE: 'students.delete',
    },
  },
  PARENTS: {
    ALL: 'parents.all',
    DIRECTORY: {
      ALL: 'parents.directory.all',
      VIEW: 'parents.directory.view',
      EDIT: 'parents.directory.update',
      DELETE: 'parents.directory.delete',
    },
    PORTAL: {
      ALL: 'parents.portal.all',
      VIEW: 'parents.portal.view',
      EDIT: 'parents.portal.update',
    },
  },
  SETTINGS: {
    VIEW: 'settings.view',
    ALL: 'settings.all',
    PAYMENT_METHODS: {
      ALL: 'settings.payment_methods.all',
      VIEW: 'settings.payment_methods.view',
      CREATE: 'settings.payment_methods.create',
      EDIT: 'settings.payment_methods.edit',
      DELETE: 'settings.payment_methods.delete',
    },
    MAIL_SETTINGS: {
      ALL: 'settings.mail_settings.all',
      VIEW: 'settings.mail_settings.view',
      EDIT: 'settings.mail_settings.edit',
    },
  },
  // Add other modules permissions here as needed
};
