export const PERMISSIONS = {
  SESSIONS: {
    CREATE: 'academics.sessions.create',
    VIEW: 'academics.sessions.view',
    EDIT: 'academics.sessions.edit',
    DELETE: 'academics.sessions.delete',
    ALL: 'academics.sessions.all',
  },
  SHIFTS: {
    CREATE: 'academics.shifts.create',
    VIEW: 'academics.shifts.view',
    EDIT: 'academics.shifts.edit',
    DELETE: 'academics.shifts.delete',
    ALL: 'academics.shifts.all',
  },
  CLASSES: {
    CREATE: 'academics.classes.create',
    VIEW: 'academics.classes.view',
    EDIT: 'academics.classes.edit',
    DELETE: 'academics.classes.delete',
    ALL: 'academics.classes.all',
  },
  CLASS_ROOMS: {
    CREATE: 'academics.class_rooms.create',
    VIEW: 'academics.class_rooms.view',
    EDIT: 'academics.class_rooms.edit',
    DELETE: 'academics.class_rooms.delete',
    ALL: 'academics.class_rooms.all',
  },
  SUBJECTS: {
    CREATE: 'academics.subjects.create',
    VIEW: 'academics.subjects.view',
    EDIT: 'academics.subjects.edit',
    DELETE: 'academics.subjects.delete',
    ALL: 'academics.subjects.all',
  },
  TIMETABLE: {
    CREATE: 'academics.timetable.create',
    VIEW: 'academics.timetable.view',
    EDIT: 'academics.timetable.edit',
    DELETE: 'academics.timetable.delete',
    ALL: 'academics.timetable.all',
  },
  ROLES: {
    VIEW: 'roles.view',
    ALL: 'roles.all',
    MANAGEMENT: {
      ALL: 'roles.management.all',
      VIEW: 'roles.management.view',
      CREATE: 'roles.management.create',
      EDIT: 'roles.management.edit',
      DELETE: 'roles.management.delete',
    },
    MATRIX: {
      ALL: 'roles.matrix.all',
      VIEW: 'roles.matrix.view',
      CREATE: 'roles.matrix.create',
      EDIT: 'roles.matrix.edit',
      DELETE: 'roles.matrix.delete',
    },
  },
  SCHOOLS_MANAGEMENT: {
    ALL: 'schools_management.all',
    SCHOOL_SUBSCRIPTIONS: {
      ALL: 'schools_management.school_subscriptions.all',
      VIEW: 'schools_management.school_subscriptions.view',
      CREATE: 'schools_management.school_subscriptions.create',
      EDIT: 'schools_management.school_subscriptions.edit',
      DELETE: 'schools_management.school_subscriptions.delete',
    },
    BANK_ACCOUNTS: {
      ALL: 'schools_management.bank_accounts.all',
      VIEW: 'schools_management.bank_accounts.view',
      CREATE: 'schools_management.bank_accounts.create',
      EDIT: 'schools_management.bank_accounts.edit',
      DELETE: 'schools_management.bank_accounts.delete',
    },
    PAYMENTS: {
      ALL: 'schools_management.payments.all',
      VIEW: 'schools_management.payments.view',
      CREATE: 'schools_management.payments.create',
      EDIT: 'schools_management.payments.edit',
      DELETE: 'schools_management.payments.delete',
    },
  },
  STAFF: {
    ALL: 'staff.all',
    VIEW: 'staff.view',
    DESIGNATIONS: {
      ALL: 'staff.designations.all',
      VIEW: 'staff.designations.view',
      CREATE: 'staff.designations.create',
      EDIT: 'staff.designations.edit',
      DELETE: 'staff.designations.delete',
    },
    DEPARTMENTS: {
      ALL: 'staff.departments.all',
      VIEW: 'staff.departments.view',
      CREATE: 'staff.departments.create',
      EDIT: 'staff.departments.edit',
      DELETE: 'staff.departments.delete',
    },
    TEACHERS: {
      ALL: 'staff.teachers.all',
      VIEW: 'staff.teachers.view',
      CREATE: 'staff.teachers.create',
      EDIT: 'staff.teachers.edit',
      DELETE: 'staff.teachers.delete',
    },
  },
  // Add other modules permissions here as needed
};
